apiVersion: kustomize.toolkit.fluxcd.io/v1beta1 
kind: Kustomization
metadata:
  name: gitops-app
  namespace: gitops-app 
spec:
  interval: 5m0s
  path: ./applications/gitops-app 
  prune: true
  sourceRef:
    kind: GitRepository 
    name: applications
  validation: client
