apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-app
  name: gitops-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - image: 'zagganas/gitops-app:'
        name: gitops-app
      - image: <image-name>:<tag>
        name: app
        ports:
        - containerPort: 8080
