apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app-deployment
  labels:
    app: gitops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: app
        image: <image-name>:<tag>
        ports:
        - containerPort: 8080
