apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-app
  name: gitops-app-deployment
  namespace: gitops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - image: zagganas/gitops-app:20220623.093854
        name: gitops-app
        ports:
        - containerPort: 8080
