apiVersion: v1
kind: Service
metadata:
  name: gitops-app-svc
  namespace: gitops-app
spec:
  type: NodePort
  selector:
    app: gitops-app
  ports:
    - port: 5000
      targetPort: 8080
      nodePort: 30007